%{ for k, v in stacks ~}
[[stack]]
description = "${v.identity.title}"
name = "${k}"

[stack.config]
auto_update = true
repo = "${github_user}/${repository}"
run_directory = "${k}"
server = "${v.target}"

[stack.config.pre_deploy]
command = "export SOPS_AGE_KEY=[[AGE_SECRET_KEY]] && find . \\( -name '*.yaml' -o -name '*.toml' \\) -exec sops decrypt -i {} \\;"

%{ endfor ~}
