[hotdog/kimbap/truenas]
process_children_only = no
recursive = yes
use_template = backup_receiver

[hotdog/kimbap/truenas-nvme]
process_children_only = no
recursive = yes
use_template = backup_receiver

[template_backup_receiver]
autoprune = yes
autosnap = no
hourly = 0
daily = 30
monthly = 12
yearly = 0
