%{ for service_name, service in services ~}
%{ if length(try(service.widgets, [])) > 0 ~}
%{ for widget in service.widgets ~}
- "${try(service.identity.name, "Uncategorized")}":
  - "${try(service.identity.name, "Service")}":
      ${indent(6, chomp(yamlencode(try(widget.widget, {}))))}
%{ endfor ~}
%{ endif ~}
%{ endfor ~}
