alerting:
  email:
    from: ${defaults.organization.email}
    host: ${defaults.resend.host}
    password: ${service.resend_api_key_sensitive}
    port: ${defaults.resend.port}
    to: ${defaults.organization.email}
    username: ${defaults.resend.username}
    default-alert:
      description: ${service.identity.description} Check Failed
      failure-threshold: 5
      send-on-resolved: true
      success-threshold: 5
endpoints:
%{ for k, server in servers ~}
  - alerts:
      - type: email
    conditions:
      - "[CONNECTED] == true"
    group: "${server.type == "router" ? "Routers" : server.type == "vm" ? "VMs" : "Servers"}"
    name: "${k}"
    url: "icmp://${server.fqdn_internal}"
%{ endfor ~}
%{ for k, svc in services ~}
%{ for url in svc.networking.urls ~}
  - alerts:
      - type: email
%{ if svc.networking.ssl_validation == false ~}
    client:
      insecure: true
%{ endif ~}
    conditions:
%{ if svc.networking.ssl && svc.networking.ssl_validation ~}
      - "[CERTIFICATE_EXPIRATION] > 48h"
%{ endif ~}
      - "[RESPONSE_TIME] < 5000"
      - "[STATUS] == any(200, 401)"
    group: "Services"
    name: "${svc.identity.description} (${svc.target})"
    url: "${svc.networking.ssl ? "https" : "http"}://${url}"
%{ endfor ~}
%{ if svc.fqdn_external != null ~}
  - alerts:
      - type: email
%{ if svc.networking.ssl_validation == false ~}
    client:
      insecure: true
%{ endif ~}
    conditions:
%{ if svc.networking.ssl && svc.networking.ssl_validation ~}
      - "[CERTIFICATE_EXPIRATION] > 48h"
%{ endif ~}
      - "[RESPONSE_TIME] < 5000"
      - "[STATUS] == any(200, 401)"
    group: "Services (External)"
    name: "${svc.identity.description} (${svc.target})"
    url: "${svc.networking.ssl ? "https" : "http"}://${svc.fqdn_external}"
%{ endif ~}
%{ if svc.fqdn_internal != null ~}
  - alerts:
      - type: email
%{ if svc.networking.ssl_validation == false ~}
    client:
      insecure: true
%{ endif ~}
    conditions:
%{ if svc.networking.ssl && svc.networking.ssl_validation ~}
      - "[CERTIFICATE_EXPIRATION] > 48h"
%{ endif ~}
      - "[RESPONSE_TIME] < 5000"
      - "[STATUS] == any(200, 401)"
    group: "Services (Internal)"
    name: "${svc.identity.description} (${svc.target})"
    url: "${svc.networking.ssl ? "https" : "http"}://${svc.fqdn_internal}"
%{ endif ~}
%{ endfor ~}
ui:
  description: ${service.identity.description}
  header: ${service.identity.name}
  title: ${service.identity.name}
