alerting:
  email:
    default-alert:
      description: ${service.identity.description} Check Failed
      failure-threshold: 5
      send-on-resolved: true
      success-threshold: 5
    from: ${defaults.organization.email}
    host: ${defaults.resend.host}
    password: $${RESEND_API_KEY}
    port: ${defaults.resend.port}
    to: ${defaults.organization.email}
    username: ${defaults.resend.username}
endpoints:
%{ for k, server in servers ~}
  - alerts:
      - type: email
    conditions:
      - "[CONNECTED] == true"
    group: "Servers (${try(server.platform, "Unknown")})"
    name: "${k} (${try(server.description, k)})"
    url: "icmp://${k}"
%{ endfor ~}
%{ for svc in values(services) ~}
%{ if try(svc.fqdn_external, null) != null && try(svc.identity.name, "") != "" ~}
  - alerts:
      - type: email
%{ if try(svc.networking.ssl_validation, true) == false ~}
    client:
      insecure: true
%{ endif ~}
    conditions:
%{ if try(svc.networking.ssl, true) && try(svc.networking.ssl_validation, true) ~}
      - "[CERTIFICATE_EXPIRATION] > 48h"
%{ endif ~}
      - "[RESPONSE_TIME] < 5000"
      - "[STATUS] == any(200, 401)"
    group: "Services (${try(svc.server, try(svc.platform, "unknown"))})"
    name: "${try(svc.identity.name, svc.fqdn_external)}"
    url: "https://${svc.fqdn_external}"
%{ endif ~}
%{ endfor ~}
ui:
  description: ${service.identity.description}
  header: ${service.identity.name}
  title: ${service.identity.name}
