# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

backend:
  base_url: https://sveltia-cms-auth.excloo.workers.dev
  branch: main
  name: github
  repo: maxexcloo/homelab

collections:
  - name: servers
    create: true
    extension: yml
    folder: data/servers
    format: yml
    identifier_field: name
    label: Servers
    fields:
      - name: name
        label: Server Name
        widget: string
      - name: type
        label: Type
        widget: select
        options:
          - lxc
          - vm
          - baremetal
          - cloud
      - name: region
        label: Region
        widget: string
        default: au
      - name: resources
        label: Resources
        multiple: true
        required: false
        widget: select
        options:
          - b2
          - cloudflare
          - cloudflared
          - docker
          - resend
          - tailscale
      - name: public_ipv4
        label: Public IPv4
        required: false
        widget: string

  - name: services
    extension: yml
    folder: data/services
    format: yml
    identifier_field: name
    label: Services
    fields:
      - name: name
        label: Service Name
        widget: string
      - name: url
        label: URL
        required: false
        widget: string
      - name: tags
        label: Tags
        required: false
        widget: list
      - name: deploy_to
        collection: servers
        display_fields: [name]
        label: Deploy To
        multiple: true
        search_fields: [name]
        value_field: name
        widget: relation

media_folder: media
