app = "${service.fly_app_name}"
primary_region = "${service.platform_config.fly.region}"

[build]
%{ if service.platform_config.fly.image != null ~}
image = "${service.platform_config.fly.image}"
%{ else ~}
dockerfile = "Dockerfile"
%{ endif ~}

[http_service]
force_https = ${service.networking.ssl}
internal_port = ${service.networking.port}
min_machines_running = ${service.platform_config.fly.min_machines_running}

[[vm]]
cpu_kind = "${service.platform_config.fly.cpu_kind}"
cpus = ${service.platform_config.fly.cpus}
memory_mb = ${service.platform_config.fly.memory_mb}
